module.exports = {
  SET_CURSOR: "SET_CURSOR",
  CLEAN_CLIPBOARD: "CLEAN_CLIPBOARD",
  CONTROL_VOLUME: "CONTROL_VOLUME",
  NEW_CLIP: "NEW_CLIP",
  SET_CLIP: "SET_CLIP",
  MAINTAIN_CLIPBOARD: "MAINTAIN_CLIPBOARD",
  ON_IMAGE: "ON_IMAGE",
  PREVENT_SLEEP: "PREVENT_SLEEP",
};