module.exports = {
  SET_CURSOR: "SET_CURSOR",
  CLEAN_CLIPBOARD: "CLEAN_CLIPBOARD",
  CONTROL_VOLUME: "CONTROL_VOLUME",
  NEW_CLIP: "NEW_CLIP",
  SET_CLIP: "SET_CLIP",
  MAINTAIN_CLIPBOARD: "MAINTAIN_CLIPBOARD",
  ON_IMAGE: "ON_IMAGE",
  PREVENT_SLEEP: "PREVENT_SLEEP",

  CURSOR_POSITIONS: {
    MIDDLE_TOP: "MIDDLE_TOP",
    TOP_RIGHT: "TOP_RIGHT",
    MIDDLE_RIGHT: "MIDDLE_RIGHT",
    BOTTOM_RIGHT: "BOTTOM_RIGHT",
    MIDDLE_BOTTOM: "MIDDLE_BOTTOM",
    BOTTOM_LEFT: "BOTTOM_LEFT",
    MIDDLE_LEFT: "MIDDLE_LEFT",
    TOP_LEFT: "TOP_LEFT",
  }
};